# Generated by Django 2.2.5 on 2019-10-06 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='keywords',
            field=models.ManyToManyField(related_name='posts', to='blog.KeyWord'),
        ),
    ]
