# Generated by Django 2.2.5 on 2019-10-06 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='main_image_url',
            field=models.CharField(default='', max_length=250),
        ),
    ]
