# Generated by Django 2.2.5 on 2019-10-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_main_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='name',
            field=models.CharField(max_length=75),
        ),
        migrations.AlterField(
            model_name='post',
            name='keywords',
            field=models.ManyToManyField(blank=True, related_name='posts', to='blog.KeyWord'),
        ),
        migrations.AlterField(
            model_name='post',
            name='main_image_url',
            field=models.ImageField(blank=True, max_length=250, upload_to=''),
        ),
    ]
