# Generated by Django 2.2.5 on 2019-10-04 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allergen',
            old_name='name',
            new_name='unique_name',
        ),
        migrations.RenameField(
            model_name='baseingredient',
            old_name='name',
            new_name='unique_name',
        ),
        migrations.RenameField(
            model_name='dish',
            old_name='name',
            new_name='unique_name',
        ),
        migrations.RenameField(
            model_name='dishcomponent',
            old_name='name',
            new_name='unique_name',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='allergens',
        ),
        migrations.AlterField(
            model_name='baseingredient',
            name='allergens',
            field=models.ManyToManyField(default=None, to='recipes.Allergen'),
        ),
    ]
