# Generated by Django 2.2.5 on 2019-10-04 17:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20191004_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='dishcomponent',
            name='custom_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
