# Generated by Django 2.2.5 on 2019-10-06 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20191004_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='baseingredient',
            name='measure_unit',
        ),
        migrations.RemoveField(
            model_name='dish',
            name='pub_date',
        ),
        migrations.AddField(
            model_name='baseingredient',
            name='is_low_lactose',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='baseingredient',
            name='allergens',
            field=models.ManyToManyField(blank=True, to='recipes.Allergen'),
        ),
    ]
