# Generated by Django 2.2.5 on 2019-10-06 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20191006_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientinstance',
            name='measure_type',
            field=models.CharField(blank=True, choices=[('weight', 'weight (e.g. grams, libs'), ('capacity', 'capacity (e.g. liters, gallons)'), ('length', 'length (e.g. centimeters, inches)'), ('absolute', 'pure number (e.g. 3)'), ('energy', 'energy (kilojoule, calories)'), ('special', 'non-standard (e.g. a pinch of, to taste, 3 leaves)')], default='weight', max_length=25),
        ),
        migrations.AddField(
            model_name='ingredientinstance',
            name='measure_unit_code',
            field=models.CharField(blank=True, default='g', max_length=25),
        ),
    ]
