# Generated by Django 2.2.5 on 2019-10-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_auto_20191006_2002'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseingredient',
            name='sugars',
            field=models.FloatField(default=0.0),
        ),
    ]
